# Load data

In [ ]:
from pandas import DataFrame, read_csv

# Function to load data
def load_data(
        data_file: str,
        n_rows: int | None = None,
) -> DataFrame:
    return read_csv(data_file, index_col='row_index', nrows=n_rows)

In [ ]:
import pandas as pd

#train_data = file_manager.load_training_data()

# load datsets
train_file = '../X_train.csv'
test_file = '../X_test.csv'
n_rows = 100_000

test_data = load_data(test_file)
# load reduced training dataset
tiny_train_data = load_data(train_file, n_rows=n_rows)

C:\Users\serra\AppData\Local\Temp\ipykernel_39292\3843374924.py:7: DtypeWarning: Columns (108,110,111,115,117,118,122,124,125,130,133,134) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(data_file, index_col='row_index', nrows=n_rows)
C:\Users\serra\AppData\Local\Temp\ipykernel_39292\3843374924.py:7: DtypeWarning: Columns (108,110,111,115,117,118,122,124,125,130,133,134) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(data_file, index_col='row_index', nrows=n_rows)

# Split raw data by variable category (piezo, weather, ...)

We are only interested in training data.

In [10]:
from pandas import DataFrame

# Function to extract variable category
def extract_category(
        df: DataFrame,
        category: str,
) -> DataFrame:
    return df[df.columns[df.columns.str.startswith(category)]]

In [11]:
# Example with meteo variables
withdrawal_variables = extract_category(tiny_train_data, 'prelev')
withdrawal_variables.head()

,prelev_structure_code_0,prelev_volume_0,prelev_usage_label_0,prelev_volume_obtention_mode_label_0,prelev_longitude_0,prelev_latitude_0,prelev_commune_code_insee_0,prelev_structure_code_1,prelev_volume_1,prelev_usage_label_1,...,prelev_latitude_1,prelev_commune_code_insee_1,prelev_structure_code_2,prelev_volume_2,prelev_usage_label_2,prelev_volume_obtention_mode_label_2,prelev_longitude_2,prelev_latitude_2,prelev_commune_code_insee_2,prelev_other_volume_sum
row_index,,,,,,,,,,,,,,,,,,,,,
39,OPR0000034438,433055.0,EAU POTABLE,Mesure directe,4.012352,49.884501,2574.0,OPR0000612762,380819.0,EAU POTABLE,...,49.884501,2574.0,OPR0000034451,301809.0,EAU POTABLE,Mesure directe,4.185969,49.825620,2031.0,5549778.0
62,OPR0000081246,638276.0,EAU POTABLE,Volume mesuré,2.627704,46.546722,3297.0,OPR0000084366,571800.0,EAU POTABLE,...,46.683740,18209.0,OPR0000084071,299400.0,IRRIGATION,Volume mesuré,2.638401,46.682624,3037.0,2394500.0
148,OPR0000047384,4844064.0,CANAUX,Mesure directe,1.832402,43.366604,11243.0,OPR0000005962,3430631.0,IRRIGATION,...,43.195658,11033.0,OPR0000005866,3397807.0,IRRIGATION,Mesure directe,1.593995,43.154755,9056.0,41529407.0
177,OPR0000049073,489771678.0,EAU TURBINEE (barrage),Mesure indirecte,2.884300,43.243859,11360.0,OPR0000049067,384114783.0,EAU TURBINEE (barrage),...,43.224692,11301.0,OPR0000049074,234271130.0,EAU TURBINEE (barrage),Mesure indirecte,2.721008,43.261030,11393.0,445416910.0
179,OPR0000049073,489771678.0,EAU TURBINEE (barrage),Mesure indirecte,2.884300,43.243859,11360.0,OPR0000049067,384114783.0,EAU TURBINEE (barrage),...,43.224692,11301.0,OPR0000049074,234271130.0,EAU TURBINEE (barrage),Mesure indirecte,2.721008,43.261030,11393.0,444055681.0

# Withdrawal Information

In [ ]:
# Display withdrawal features information
withdrawal_variables.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 39 to 3293997
Data columns (total 22 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   prelev_structure_code_0               80570 non-null  object
 1   prelev_volume_0                       80570 non-null  float64
 2   prelev_usage_label_0                  80570 non-null  object
 3   prelev_volume_obtention_mode_label_0  80570 non-null  object
 4   prelev_longitude_0                    80570 non-null  float64
 5   prelev_latitude_0                     80570 non-null  float64
 6   prelev_commune_code_insee_0           80570 non-null  float64
 7   prelev_structure_code_1               80548 non-null  object
 8   prelev_volume_1                       80548 non-null  float64
 9   prelev_usage_label_1                  80548 non-null  object
 10  prelev_volume_obtention_mode_label_1  80548 non-null  object
 11  prelev_longitude_1                    80548 non-null  float64
 12  prelev_latitude_1                     80548 non-null  float64
 13  prelev_commune_code_insee_1           80548 non-null  float64
 14  prelev_structure_code_2               80449 non-null  object
 15  prelev_volume_2                       80449 non-null  float64
 16  prelev_usage_label_2                  80449 non-null  object
 17  prelev_volume_obtention_mode_label_2  80449 non-null  object
 18  prelev_longitude_2                    80449 non-null  float64
 19  prelev_latitude_2                     80449 non-null  float64
 20  prelev_commune_code_insee_2           80449 non-null  float64
 21  prelev_other_volume_sum               86591 non-null  float64
dtypes: float64(13), object(9)
memory usage: 17.5+ MB

In [13]:
# Create a copy to avoid modifying a slice of the DataFrame
withdrawal_variables = withdrawal_variables.copy()

# Loop to drop the specified columns
for i in range(3):
    columns_to_drop = [
        f"prelev_structure_code_{i}",
        f"prelev_usage_label_{i}",
        f"prelev_volume_obtention_mode_label_{i}",
        f"prelev_longitude_{i}",
        f"prelev_latitude_{i}",
        f"prelev_commune_code_insee_{i}"
    ]
    withdrawal_variables.drop(columns=columns_to_drop, inplace=True, axis=1)

# Handle NaN values for specific columns
cols_to_merge = ["prelev_volume_0", "prelev_volume_1", "prelev_volume_2", "prelev_other_volume_sum"]
withdrawal_variables[cols_to_merge] = withdrawal_variables[cols_to_merge].fillna(0)

# Create a new column for the total volume
withdrawal_variables["prelev_volume_total"] = withdrawal_variables[cols_to_merge].sum(axis=1)

# Drop the individual volume columns
withdrawal_variables.drop(columns=cols_to_merge, inplace=True)

In [ ]:
# Display new withdrawal columns
withdrawal_variables.head()

           prelev_volume_total
row_index
39                6.665461e+06
62                3.903976e+06
148               5.320191e+07
177               1.553575e+09
179               1.552213e+09